"""The website's data: generated by the real engine (demo/build_site.py), and up to date."""

import importlib.util
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
_spec = importlib.util.spec_from_file_location("build_site", ROOT / "demo" / "build_site.py")
build_site = importlib.util.module_from_spec(_spec)
sys.modules[_spec.name] = build_site
_spec.loader.exec_module(build_site)


def value(js: str):
    """The JSON a generated `window.X = ...;` file holds."""
    return json.loads(js[js.index("=") + 1:].strip().rstrip(";"))


class SiteData(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.files = build_site.build()      # also fails if a Try-it example changed its verdict
        cls.incidents = {i["name"]: i for i in value(cls.files[build_site.DATA / "incidents.js"])}

    def test_site_data_is_up_to_date(self):
        stale = [p.relative_to(ROOT).as_posix() for p in build_site.stale(self.files)]
        self.assertEqual(stale, [], "run: python demo/build_site.py, then commit site/data/")

    def test_every_incident_has_its_story(self):
        self.assertGreaterEqual(len(self.incidents), 6)
        for name, inc in self.incidents.items():
            with self.subTest(name):
                story = inc["story"]
                self.assertTrue(story["files"] and all(f["lines"] for f in story["files"]))
                self.assertTrue(story["map"]["nodes"])
                self.assertTrue(inc.get("damage"), "what it cost, from a cited source")
                self.assertTrue(inc.get("catch") or story["findings"], "what the rule looks for")

    def test_the_sensor_story_is_caught_in_a_file_nobody_touched(self):
        story = self.incidents["sensor-signature-break"]["story"]
        self.assertEqual((story["verdict"], story["rules"]), ("block", {"signature-break": "caught"}))
        collector = next(f for f in story["files"] if f["path"] == "sensor/collector.py")
        self.assertEqual((collector["state"], collector["marks"]), ("untouched", [11]))
        self.assertEqual([n["id"] for n in story["map"]["nodes"] if n["finding"]],
                         ["sensor.collector.collect"])

    def test_the_browser_bundle_runs_on_its_own(self):
        # what Pyodide does: import magellan_lite from the bundle alone, then check a change
        bundle = value(self.files[build_site.DATA / "engine.js"])
        self.assertNotIn("magellan_lite/git.py", bundle["files"])     # no git in a browser
        with tempfile.TemporaryDirectory() as tmp:
            for path, source in bundle["files"].items():
                (Path(tmp) / path).parent.mkdir(parents=True, exist_ok=True)
                (Path(tmp) / path).write_text(source, encoding="utf-8")
            code = ("import json, sys; sys.path.insert(0, sys.argv[1])\n"
                    "import magellan_lite\n"
                    "from magellan_lite.web import check_with_map\n"
                    "r = check_with_map({'m.py': 'def f(x):\\n    return x\\n', 'u.py': "
                    "'from m import f\\n\\n\\ndef g():\\n    return f(1)\\n'},\n"
                    "                   {'m.py': 'def f(x, y):\\n    return x\\n', 'u.py': "
                    "'from m import f\\n\\n\\ndef g():\\n    return f(1)\\n'})\n"
                    "from magellan_lite.web import team_live\n"
                    "t = team_live({'m.py': 'def f(x):\\n    return x\\n'},\n"
                    "              {'a': {'m.py': 'def f(x, y):\\n    return x\\n'},\n"
                    "               'b': {'m.py': 'def f(x):\\n    return x\\n', 'u.py': "
                    "'from m import f\\n\\n\\ndef g():\\n    return f(1)\\n'}})\n"
                    "print(json.dumps([magellan_lite.__file__, r['verdict'],"
                    " [f['rule'] for f in r['findings']], t['pairs'][0]['verdict']]))")
            out = subprocess.run([sys.executable, "-I", "-c", code, tmp], capture_output=True,
                                 text=True, check=True).stdout
        where, verdict, rules, together = json.loads(out)
        self.assertTrue(where.startswith(tmp))
        self.assertEqual((verdict, rules), ("block", ["signature-break"]))
        self.assertEqual(together, "block")                 # the Team suite's check, too

    def test_pages_sends_the_same_security_headers_as_the_server(self):
        from magellan_lite import security
        written = self.files[build_site.SITE / "_headers"].splitlines()
        self.assertIn("/*", written)
        for k, v in security.headers(build_site.SITE).items():
            self.assertIn(f"  {k}: {v}", written)
        csp = security.csp(build_site.SITE)
        for needed in ("https://api.github.com", "https://raw.githubusercontent.com",
                       "https://cdn.jsdelivr.net", "'wasm-unsafe-eval'", "worker-src 'self'"):
            self.assertIn(needed, csp)

    def test_every_page_shares_one_inline_script(self):
        # the CSP allows inline scripts by hash: a second, different one would be blocked
        from magellan_lite import security
        pages = sorted(p.name for p in build_site.SITE.glob("*.html"))
        self.assertEqual(pages, ["index.html", "scene.html", "suite.html"])
        self.assertEqual(len(security.inline_script_hashes(build_site.SITE)), 1)


if __name__ == "__main__":
    unittest.main()
