"""The website's data: generated by the real engine (demo/build_site.py), and up to date."""

import importlib.util
import json
import re
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
_spec = importlib.util.spec_from_file_location("build_site", ROOT / "demo" / "build_site.py")
build_site = importlib.util.module_from_spec(_spec)
sys.modules[_spec.name] = build_site
_spec.loader.exec_module(build_site)


def value(js: str):
    """The JSON a generated `window.X = ...;` file holds."""
    return json.loads(js[js.index("=") + 1:].strip().rstrip(";"))


#: a C function gains a parameter; load.c, untouched, still calls it the old way
_PARSE = "int parse(const char *s, int len) {\n    return len;\n}\n"
_LOAD = '#include "parse.h"\nint load(void) {\n    return parse("x", 1);\n}\n'
C_CHANGE = ({"parse.c": _PARSE, "load.c": _LOAD},
            {"parse.c": _PARSE.replace("int len)", "int len, int flags)"), "load.c": _LOAD})


def run_bundles(bundles: list[dict], code: str, *args: str) -> tuple[str, list]:
    """What Pyodide does: the bundles' files in a folder of their own, and ``code`` run by a
    Python that sees nothing else (-I: no site-packages, not this checkout). ``code`` gets the
    folder on sys.path and ``args`` as sys.argv[2:], and prints JSON. Returns the folder and
    that JSON."""
    with tempfile.TemporaryDirectory() as tmp:
        for bundle in bundles:
            for path, source in bundle["files"].items():
                (Path(tmp) / path).parent.mkdir(parents=True, exist_ok=True)
                (Path(tmp) / path).write_text(source, encoding="utf-8")
        out = subprocess.run([sys.executable, "-I", "-c",
                              "import json, sys; sys.path.insert(0, sys.argv[1])\n" + code,
                              tmp, *args], capture_output=True, text=True, check=True).stdout
    return tmp, json.loads(out)


class SiteData(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.files = build_site.build()      # also fails if a Try-it example changed its verdict
        cls.incidents = {i["name"]: i for i in value(cls.files[build_site.DATA / "incidents.js"])}

    def test_site_data_is_up_to_date(self):
        stale = [p.relative_to(ROOT).as_posix() for p in build_site.stale(self.files)]
        self.assertEqual(stale, [], "run: python demo/build_site.py, then commit site/data/")

    def test_every_incident_has_its_story(self):
        self.assertGreaterEqual(len(self.incidents), 6)
        for name, inc in self.incidents.items():
            with self.subTest(name):
                story = inc["story"]
                self.assertTrue(story["files"] and all(f["lines"] for f in story["files"]))
                self.assertTrue(story["map"]["nodes"])
                self.assertTrue(inc.get("damage"), "what it cost, from a cited source")
                self.assertTrue(inc.get("catch") or story["findings"], "what the rule looks for")

    def test_the_sensor_story_is_caught_in_a_file_nobody_touched(self):
        story = self.incidents["sensor-signature-break"]["story"]
        self.assertEqual((story["verdict"], story["rules"]), ("block", {"signature-break": "caught"}))
        collector = next(f for f in story["files"] if f["path"] == "sensor/collector.py")
        self.assertEqual((collector["state"], collector["marks"]), ("untouched", [11]))
        self.assertEqual([n["id"] for n in story["map"]["nodes"] if n["finding"]],
                         ["sensor.collector.collect"])

    def test_the_browser_bundle_runs_on_its_own(self):
        # what Pyodide does: import magellan_lite from the bundle alone, then check a change
        bundle = value(self.files[build_site.DATA / "engine.js"])
        self.assertNotIn("magellan_lite/git.py", bundle["files"])     # no git in a browser
        tmp, out = run_bundles([bundle], (
            "import magellan_lite\n"
            "from magellan_lite.web import check_with_map\n"
            "r = check_with_map({'m.py': 'def f(x):\\n    return x\\n', 'u.py': "
            "'from m import f\\n\\n\\ndef g():\\n    return f(1)\\n'},\n"
            "                   {'m.py': 'def f(x, y):\\n    return x\\n', 'u.py': "
            "'from m import f\\n\\n\\ndef g():\\n    return f(1)\\n'})\n"
            "from magellan_lite.web import team_live\n"
            "t = team_live({'m.py': 'def f(x):\\n    return x\\n'},\n"
            "              {'a': {'m.py': 'def f(x, y):\\n    return x\\n'},\n"
            "               'b': {'m.py': 'def f(x):\\n    return x\\n', 'u.py': "
            "'from m import f\\n\\n\\ndef g():\\n    return f(1)\\n'}})\n"
            # half-typed code in Try it: a file that doesn't parse is reported, not a crash
            # (it is tried as Python 2 first: the bundle carries that reader)
            "h = check_with_map({'m.py': 'x = 1\\n'}, {'m.py': 'x = (1\\n'})\n"
            "print(json.dumps([magellan_lite.__file__, r['verdict'],"
            " [f['rule'] for f in r['findings']], t['pairs'][0]['verdict'], h['errors']]))"))
        where, verdict, rules, together, half_typed = out
        self.assertTrue(where.startswith(tmp))
        self.assertEqual((verdict, rules), ("block", ["signature-break"]))
        self.assertEqual(together, "block")                 # the Team suite's check, too
        self.assertEqual(len(half_typed), 1)
        self.assertIn("m.py:1", half_typed[0])

    def test_the_browser_bundle_is_python_only(self):
        # engine.js carries no other language's frontend (polyglot.js does, loaded only when a
        # repository has such files): a C change is skipped, and the report says so
        bundle = value(self.files[build_site.DATA / "engine.js"])
        self.assertEqual(sorted(p for p in bundle["files"] if "/polyglot/" in p),
                         sorted(f"magellan_lite/{p}" for p in build_site.PY2_READER))
        _, (verdict, errors) = run_bundles([bundle], (
            "from magellan_lite.web import check_with_map\n"
            "before, after = json.loads(sys.argv[2])\n"
            "r = check_with_map(before, after)\n"
            "print(json.dumps([r['verdict'], r['errors']]))"), json.dumps(C_CHANGE))
        self.assertEqual(verdict, "ok")
        self.assertIn("C files skipped", " ".join(errors))

    def test_the_other_languages_bundle_holds_the_rest_of_the_frontends(self):
        engine = value(self.files[build_site.DATA / "engine.js"])["files"]
        others = value(self.files[build_site.DATA / "polyglot.js"])["files"]
        self.assertFalse(set(engine) & set(others))
        pkg = ROOT / "magellan_lite" / "polyglot"
        vendored = {p.relative_to(ROOT).as_posix() for p in pkg.rglob("*")
                    if p.is_file() and "__pycache__" not in p.parts and p.suffix != ".pyc"}
        self.assertEqual({p for p in set(engine) | set(others) if "/polyglot/" in p}, vendored)
        # with the data files the frontends read (pyproject.toml's package-data)
        self.assertIn("magellan_lite/polyglot/typescript/ts_extract.js", others)
        self.assertIn("magellan_lite/polyglot/cpp/legacy_include/iostream.h", others)

    def test_the_browser_bundles_catch_a_c_change(self):
        # the Team suite's worker on a repository with C files: engine.js, then polyglot.js
        bundles = [value(self.files[build_site.DATA / n]) for n in ("engine.js", "polyglot.js")]
        tmp, (where, verdict, found, errors, member) = run_bundles(bundles, (
            "import magellan_lite.polyglot\n"
            "from magellan_lite.web import check_with_map, team_live\n"
            "before, after = json.loads(sys.argv[2])\n"
            "r = check_with_map(before, after)\n"
            "t = team_live(before, {'ann': after})\n"
            "print(json.dumps([magellan_lite.polyglot.__file__, r['verdict'],"
            " [(f['rule'], f['path']) for f in r['findings']], r['errors'],"
            " t['members'][0]['verdict']]))"), json.dumps(C_CHANGE))
        self.assertTrue(where.startswith(tmp))
        self.assertEqual((verdict, found, errors), ("block", [["signature-break", "load.c"]], []))
        self.assertEqual(member, "block")                   # the Team suite's check, too

    def test_the_team_suite_reads_the_files_the_engine_reads(self):
        # site/js/github.js keeps its own copy of languages.py's suffixes: the same list
        from magellan_lite.languages import LANGUAGE_OF
        source = (build_site.SITE / "js" / "github.js").read_text(encoding="utf-8")
        listed = re.search(r"const SUFFIXES = new Set\((\[.*?\])\);", source, re.S)
        self.assertIsNotNone(listed, "github.js: const SUFFIXES = new Set([...]);")
        self.assertEqual(sorted(json.loads(listed.group(1))), sorted(LANGUAGE_OF))

    def test_pages_sends_the_same_security_headers_as_the_server(self):
        from magellan_lite import security
        written = self.files[build_site.SITE / "_headers"].splitlines()
        self.assertIn("/*", written)
        for k, v in security.headers(build_site.SITE).items():
            self.assertIn(f"  {k}: {v}", written)
        csp = security.csp(build_site.SITE)
        for needed in ("https://api.github.com", "https://raw.githubusercontent.com",
                       "https://cdn.jsdelivr.net", "'wasm-unsafe-eval'", "worker-src 'self'"):
            self.assertIn(needed, csp)

    def test_every_page_shares_one_inline_script(self):
        # the CSP allows inline scripts by hash: a second, different one would be blocked
        from magellan_lite import security
        pages = sorted(p.name for p in build_site.SITE.glob("*.html"))
        self.assertEqual(pages, ["index.html", "scene.html", "suite.html"])
        self.assertEqual(len(security.inline_script_hashes(build_site.SITE)), 1)


if __name__ == "__main__":
    unittest.main()
